name: Node.js CI

on:
  push:
    branches:
      - master
  schedule:
    - cron: '30 1,16 * * *'

jobs:
  retrieve_data:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: node index.js
      env:
        CI: true
        slack_webhook: ${{ secrets.slack_webhook }}
        action_slack: ${{ secrets.action_slack }}

  save_data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: committing results
    - run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git pull github ${GITHUB_REF} --ff-only
        git add ...
        git commit -m "Update native model"
        git push github HEAD:${GITHUB_REF}
